// Barrel — all design tokens consumable as a single typed import.
//
//   import { colorTokens, typographyTokens, motionTokens } from '@solo/ui/tokens';
//
// The CSS variable form of each token is in packages/ui/src/tokens.css,
// generated by scripts/build-tokens.ts.

export { colorTokens, type ColorTokenName } from './colors';
export { typographyTokens, type FontSizeName, type FontWeightName } from './typography';
export { spacingTokens, type SpacingName } from './spacing';
export { radiiTokens, type RadiusName } from './radii';
export { shadowTokens, glowPresets, type ShadowName } from './shadows';
export { motionTokens, type DurationName, type EasingName, type KeyframeName } from './motion';
export { zIndexTokens, type ZIndexName } from './z-index';
export { chromeTokens, type ChromeTokenName } from './chrome';
