/**
 * Generator — reads packages/ui/src/tokens/*.ts and writes tokens.css.
 *
 * tokens.css is NEVER hand-edited. Run via:
 *   bun run --filter @solo/ui build-tokens
 *
 * The output is structured:
 *   :root         → light values + shared tokens (typography, spacing, radii, motion, z-index)
 *   html.dark     → dark-mode color + shadow overrides
 *   @keyframes    → every keyframe from motion.ts
 */

import { writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import {
  chromeTokens,
  colorTokens,
  glowPresets,
  motionTokens,
  radiiTokens,
  shadowTokens,
  spacingTokens,
  typographyTokens,
  zIndexTokens,
} from '../src/tokens';

function kebab(camel: string): string {
  return camel.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();
}

function colorBlock(set: typeof colorTokens.light): string[] {
  return Object.entries(set).map(([name, value]) => `  --color-${kebab(name)}: ${value};`);
}

function shadowBlock(set: typeof shadowTokens.light): string[] {
  return Object.entries(set).map(([name, value]) => `  --shadow-${kebab(name)}: ${value};`);
}

function buildRootLight(): string {
  const lines: string[] = [];

  lines.push(':root {');
  lines.push('  color-scheme: light dark;');
  lines.push('');
  lines.push('  /* Colors (light) */');
  lines.push(...colorBlock(colorTokens.light));
  lines.push('');
  lines.push('  /* Typography — font families */');
  for (const [name, value] of Object.entries(typographyTokens.fontFamily)) {
    lines.push(`  --font-${kebab(name)}: ${value};`);
  }
  lines.push('');
  lines.push('  /* Typography — font sizes */');
  for (const [name, value] of Object.entries(typographyTokens.fontSize)) {
    lines.push(`  --text-${name}: ${value};`);
  }
  lines.push('');
  lines.push('  /* Typography — weights / line-heights / tracking / features */');
  for (const [name, value] of Object.entries(typographyTokens.fontWeight)) {
    lines.push(`  --font-weight-${kebab(name)}: ${value};`);
  }
  for (const [name, value] of Object.entries(typographyTokens.lineHeight)) {
    lines.push(`  --leading-${kebab(name)}: ${value};`);
  }
  for (const [name, value] of Object.entries(typographyTokens.letterSpacing)) {
    lines.push(`  --tracking-${kebab(name)}: ${value};`);
  }
  for (const [name, value] of Object.entries(typographyTokens.fontFeatureSettings)) {
    lines.push(`  --font-feature-${kebab(name)}: ${value};`);
  }
  lines.push('');
  lines.push('  /* Spacing */');
  for (const [name, value] of Object.entries(spacingTokens)) {
    const safe = String(name).replace('.', '_');
    lines.push(`  --space-${safe}: ${value};`);
  }
  lines.push('');
  lines.push('  /* Radii */');
  for (const [name, value] of Object.entries(radiiTokens)) {
    lines.push(`  --radius-${kebab(name)}: ${value};`);
  }
  lines.push('');
  lines.push('  /* Shadows (light) */');
  lines.push(...shadowBlock(shadowTokens.light));
  for (const [name, value] of Object.entries(glowPresets)) {
    lines.push(`  --shadow-glow-${kebab(name)}: ${value};`);
  }
  lines.push('');
  lines.push('  /* Motion */');
  for (const [name, value] of Object.entries(motionTokens.duration)) {
    lines.push(`  --duration-${kebab(name)}: ${value}ms;`);
  }
  for (const [name, value] of Object.entries(motionTokens.easing)) {
    lines.push(`  --ease-${kebab(name)}: ${value};`);
  }
  for (const [name, value] of Object.entries(motionTokens.animations)) {
    lines.push(`  --animate-${name}: ${value};`);
  }
  lines.push('');
  lines.push('  /* Z-index */');
  for (const [name, value] of Object.entries(zIndexTokens)) {
    lines.push(`  --z-${kebab(name)}: ${value};`);
  }
  lines.push('');
  lines.push('  /* Chrome — IDE-specific measurements (Codex-derived) */');
  for (const [name, value] of Object.entries(chromeTokens)) {
    lines.push(`  --chrome-${kebab(name)}: ${value};`);
  }
  lines.push('}');
  return lines.join('\n');
}

function buildRootDark(): string {
  const lines: string[] = [];
  lines.push('html.dark {');
  lines.push('  color-scheme: dark;');
  lines.push('');
  lines.push('  /* Colors (dark) */');
  lines.push(...colorBlock(colorTokens.dark));
  lines.push('');
  lines.push('  /* Shadows (dark) */');
  lines.push(...shadowBlock(shadowTokens.dark));
  lines.push('}');
  return lines.join('\n');
}

function buildKeyframes(): string {
  return Object.values(motionTokens.keyframes).join('\n\n');
}

async function main() {
  const header = [
    '/*',
    ' * packages/ui/src/tokens.css',
    ' * GENERATED by packages/ui/scripts/build-tokens.ts — do not edit.',
    ` * generated: ${new Date().toISOString()}`,
    ' */',
    '',
  ].join('\n');

  const content = [
    header,
    buildRootLight(),
    '',
    buildRootDark(),
    '',
    '/* Keyframes */',
    buildKeyframes(),
    '',
  ].join('\n');

  const outPath = join(import.meta.dir, '..', 'src', 'tokens.css');
  await writeFile(outPath, content, 'utf8');
  console.log(`[build-tokens] wrote ${outPath} (${content.length} bytes)`);
}

if (import.meta.main) {
  main().catch((err) => {
    console.error(err);
    process.exit(1);
  });
}
