// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How the agent task execution session is constrained.
 * Distinct from the settings-level `PermissionMode` (which controls the
 * interactive agent permission pipeline). This type governs per-task
 * autonomous execution safety.
 */
export type AgentPermissionMode = "ask" | "plan" | "accept_edits" | "bypass";
