// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentPermissionMode } from "./AgentPermissionMode";
import type { ExecutionLocation } from "./ExecutionLocation";

/**
 * Per-task executor configuration.
 */
export type AgentConfig = { 
/**
 * Provider override; None → use the app's currently-active provider
 * (anthropic, openai, etc.).
 */
provider?: string, 
/**
 * Model override; None → system default.
 */
model?: string, 
/**
 * Explicit skill allow-list; None → planner/default picks.
 */
skills?: Array<string>, permission_mode: AgentPermissionMode, execution_location: ExecutionLocation, 
/**
 * Extra command patterns to block (merged with global deny-list).
 */
deny_list: Array<string>, 
/**
 * Optional network allow-list. None = open; Some([]) = offline.
 */
network_allow_list?: Array<string>, };
