// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CloudSyncState } from "./CloudSyncState";
import type { PermissionMode } from "./PermissionMode";
import type { SessionGoal } from "./SessionGoal";
import type { SoloSettings } from "./SoloSettings";
import type { VoiceMode } from "./VoiceMode";
import type { VoiceModelProgress } from "./VoiceModelProgress";
import type { VoicePipelineState } from "./VoicePipelineState";
import type { VoiceTranscriptResult } from "./VoiceTranscriptResult";
import type { WorktreeInfo } from "./WorktreeInfo";

/**
 * Events emitted from the backend to the frontend.
 *
 * Note: Agent events now flow through dedicated Tauri emit channels
 * (agent:message, agent:permission_request, etc.) from the agent bridge,
 * not through BackendEvent.
 */
export type BackendEvent = { "type": "terminal:data", "payload": { id: string, data: string, } } | { "type": "terminal:exit", "payload": { id: string, code: number | null, } } | { "type": "file:changed", "payload": { path: string, } } | { "type": "file:created", "payload": { path: string, } } | { "type": "file:deleted", "payload": { path: string, } } | { "type": "file:renamed", "payload": { old_path: string, new_path: string, } } | { "type": "parse:complete", "payload": { path: string, symbol_count: number, } } | { "type": "git:progress", "payload": { operation: string, message: string, } } | { "type": "git:changes_updated", "payload": Record<string, never> } | { "type": "worktree:progress", "payload": { worktree_id: string, message: string, } } | { "type": "worktree:ready", "payload": { worktree_id: string, info: WorktreeInfo, } } | { "type": "worktree:error", "payload": { worktree_id: string, error: string, } } | { "type": "worktree:removed", "payload": { worktree_id: string, } } | { "type": "worktree:setup_progress", "payload": { worktree_id: string, command: string, output: string, is_error: boolean, is_complete: boolean, } } | { "type": "update:available", "payload": { version: string, body: string | null, date: string | null, } } | { "type": "update:progress", "payload": { chunk_length: number, content_length: bigint | null, } } | { "type": "update:ready", "payload": Record<string, never> } | { "type": "update:error", "payload": { error: string, } } | { "type": "vault:entry_added", "payload": { entry_id: string, } } | { "type": "vault:entry_updated", "payload": { entry_id: string, } } | { "type": "vault:entry_deleted", "payload": { entry_id: string, } } | { "type": "vault:index_progress", "payload": { entry_id: string, 
/**
 * One of: validate, extract, chunk, embed, store, notify
 */
stage: string, 
/**
 * [0, 100]
 */
pct: number, } } | { "type": "vault:cloud_sync_updated", "payload": { entry_id: string, state: CloudSyncState, } } | { "type": "vault:unsorted_count_changed", "payload": { count: number, } } | { "type": "vault:backfill_progress", "payload": { 
/**
 * Total chunks pending embedding at start of this backfill run.
 */
total: bigint, 
/**
 * Chunks successfully embedded so far (cumulative across batches).
 */
completed: bigint, 
/**
 * Chunks that failed (dim mismatch, corrupt BLOB, provider error).
 */
failed: bigint, 
/**
 * Wall-clock milliseconds elapsed since backfill started.
 */
elapsed_ms: bigint, 
/**
 * `true` on the last event for this run; `false` for ticks.
 */
done: boolean, } } | { "type": "settings:changed", "payload": { settings: SoloSettings, } } | { "type": "session:goal_captured", "payload": { goal: SessionGoal, } } | { "type": "session:mode_changed", "payload": { session_id: string, mode: PermissionMode, } } | { "type": "voice:state", "payload": { mode: VoiceMode, state: VoicePipelineState, } } | { "type": "voice:level", "payload": { rms: number, } } | { "type": "voice:transcript", "payload": { result: VoiceTranscriptResult, } } | { "type": "voice:error", "payload": { message: string, } } | { "type": "voice:model_progress", "payload": { progress: VoiceModelProgress, } } | { "type": "tasks:changed", "payload": { task_ids: Array<string>, } };
