// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One row of the usage heatmap. Raw per-day counters; the client computes
 * the usage score so weight calibration stays out of the server.
 */
export type DailyActivityEntry = { date: string, commits: bigint, tokens: bigint, worktrees: bigint, sessions: bigint, messages: bigint, };
