// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Event trigger kinds. v1 ships one variant; enum lets Phase 5+ add more without migration.
 */
export type EventKind = "agent_session_ended";
