// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where the agent runs.
 */
export type ExecutionLocation = "main_workspace" | "worktree";
