// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Preset cadence for scheduled tasks.
 */
export type PresetKind = "hourly" | "daily" | "weekly" | "monthly";
