// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Lightweight view of one profile for UI display.
 *
 * Intentionally does NOT carry tokens — callers only need display fields.
 */
export type ProfileSummary = { 
/**
 * Profile key (e.g. "default", "work").
 */
name: string, 
/**
 * Display label — typically the account email. `""` if unknown.
 */
email: string, 
/**
 * True if this is the active profile for its provider.
 */
isActive: boolean, 
/**
 * Seconds until the token expires. `None` if no token stored (shouldn't happen).
 */
expiresInSeconds: bigint | null, };
