// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EventKind } from "./EventKind";
import type { PresetKind } from "./PresetKind";

/**
 * How a task fires automatically. `None` on Task = one-shot / manual.
 */
export type Schedule = { "kind": "one_shot", "data": { at: bigint, } } | { "kind": "cron", "data": { expr: string, next_fire: bigint, } } | { "kind": "preset", "data": { kind: PresetKind, hour: number, minute: number, weekday: number | null, next_fire: bigint, } } | { "kind": "event_triggered", "data": { event: EventKind, } };
