// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentConfig } from "./AgentConfig";
import type { Schedule } from "./Schedule";
import type { Subtask } from "./Subtask";
import type { TaskPriority } from "./TaskPriority";
import type { TaskStatus } from "./TaskStatus";

/**
 * Partial update for `task_update` — any `Some` field is written; `None` leaves alone.
 */
export type TaskPatch = { title?: string, description?: string, status?: TaskStatus, priority?: TaskPriority, catch_up_on_launch?: boolean, agent_config?: AgentConfig, schedule?: Schedule, 
/**
 * Bulk-replace subtasks. Rarely used from the UI (we prefer fine-grained
 * `task_subtask_*` commands); kept for completeness.
 */
subtasks?: Array<Subtask>, 
/**
 * Bulk-replace label ids. Fine-grained operations live on
 * `task_label_add` / `task_label_remove`; this is for atomic sets.
 */
label_ids?: Array<string>, 
/**
 * Explicit-null semantics: omit to leave unchanged; pass `null` to clear.
 * `TaskPatchNullable<String>` encodes this via an outer Option of inner
 * Option; we keep it simple with a separate boolean flag.
 */
project_id?: string, clear_project?: boolean, cycle_id?: string, clear_cycle?: boolean, };
