// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaskPriority } from "./TaskPriority";
import type { TaskStatus } from "./TaskStatus";

/**
 * Partial update for `task_update` — any `Some` field is written; `None` leaves alone.
 */
export type TaskPatch = { title?: string, description?: string, status?: TaskStatus, priority?: TaskPriority, catch_up_on_launch?: boolean, };
