// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Executor } from "./Executor";
import type { TaskPriority } from "./TaskPriority";
import type { TaskStatus } from "./TaskStatus";

/**
 * Filter applied on `task_list`.
 */
export type TaskListFilters = { status?: Array<TaskStatus>, executor?: Executor, priority?: Array<TaskPriority>, query?: string, };
