// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentConfig } from "./AgentConfig";
import type { ContextAnchor } from "./ContextAnchor";
import type { Executor } from "./Executor";
import type { Schedule } from "./Schedule";
import type { TaskOrigin } from "./TaskOrigin";
import type { TaskPriority } from "./TaskPriority";
import type { TaskRun } from "./TaskRun";
import type { TaskStatus } from "./TaskStatus";

/**
 * The core task entity. `agent_config` + `schedule` are `Option` so Phase 1
 * (manual-only) persists `None` without schema churn.
 */
export type Task = { id: string, title: string, description: string, status: TaskStatus, executor: Executor, priority: TaskPriority, created_at: bigint, updated_at: bigint, 
/**
 * `None` for manual tasks (Phase 1). Activated in Phase 2.
 */
agent_config?: AgentConfig, 
/**
 * `None` for one-shot tasks. Activated in Phase 4.
 */
schedule?: Schedule, context_anchors: Array<ContextAnchor>, runs: Array<TaskRun>, last_error: string | null, catch_up_on_launch: boolean, origin: TaskOrigin, };
