// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to send a message to the AI agent
 */
export type AgentSendMessageRequest = { 
/**
 * Conversation ID (optional, creates new if not provided)
 */
conversation_id: string | null, 
/**
 * User message content
 */
content: string, 
/**
 * Optional system prompt override
 */
system_prompt: string | null, };
