// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A tool call from the agent
 */
export type AgentToolCall = { 
/**
 * Tool call ID
 */
id: string, 
/**
 * Tool name
 */
name: string, 
/**
 * Tool arguments as JSON
 */
arguments: string, };
