// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentToolCall } from "./AgentToolCall";

/**
 * A message in the conversation
 */
export type AgentMessage = { 
/**
 * Message role (user, assistant, system)
 */
role: string, 
/**
 * Message content
 */
content: string, 
/**
 * Optional tool calls (for assistant messages)
 */
tool_calls: Array<AgentToolCall> | null, };
