// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentBlock } from "./ContentBlock";

/**
 * A message in the conversation
 */
export type AgentMessage = { 
/**
 * Message role (user, assistant, system)
 */
role: string, 
/**
 * Structured content blocks
 */
content: Array<ContentBlock>, 
/**
 * Flattened text for display (computed from text blocks)
 */
text: string | null, };
