// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorktreeInfo } from "./WorktreeInfo";

/**
 * Events emitted from the backend to the frontend.
 *
 * Note: Agent events now flow through dedicated Tauri emit channels
 * (agent:message, agent:permission_request, etc.) from the agent bridge,
 * not through BackendEvent.
 */
export type BackendEvent = { "type": "terminal:data", "payload": { id: string, data: string, } } | { "type": "terminal:exit", "payload": { id: string, code: number | null, } } | { "type": "file:changed", "payload": { path: string, } } | { "type": "file:created", "payload": { path: string, } } | { "type": "file:deleted", "payload": { path: string, } } | { "type": "file:renamed", "payload": { old_path: string, new_path: string, } } | { "type": "parse:complete", "payload": { path: string, symbol_count: number, } } | { "type": "git:progress", "payload": { operation: string, message: string, } } | { "type": "git:changes_updated", "payload": Record<string, never> } | { "type": "worktree:progress", "payload": { worktree_id: string, message: string, } } | { "type": "worktree:ready", "payload": { worktree_id: string, info: WorktreeInfo, } } | { "type": "worktree:error", "payload": { worktree_id: string, error: string, } } | { "type": "worktree:removed", "payload": { worktree_id: string, } } | { "type": "worktree:setup_progress", "payload": { worktree_id: string, command: string, output: string, is_error: boolean, is_complete: boolean, } };
