// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentMessage } from "./AgentMessage";
import type { AgentToolCall } from "./AgentToolCall";

/**
 * Events emitted from the backend to the frontend
 */
export type BackendEvent = { "type": "terminal:data", "payload": { id: string, data: string, } } | { "type": "terminal:exit", "payload": { id: string, code: number | null, } } | { "type": "agent:chunk", "payload": { conversation_id: string, content: string, } } | { "type": "agent:tool_start", "payload": { conversation_id: string, tool_call: AgentToolCall, } } | { "type": "agent:tool_end", "payload": { conversation_id: string, tool_call_id: string, result: string, } } | { "type": "agent:complete", "payload": { conversation_id: string, message: AgentMessage, } } | { "type": "agent:error", "payload": { conversation_id: string, error: string, } } | { "type": "file:changed", "payload": { path: string, } } | { "type": "file:created", "payload": { path: string, } } | { "type": "file:deleted", "payload": { path: string, } } | { "type": "file:renamed", "payload": { old_path: string, new_path: string, } } | { "type": "parse:complete", "payload": { path: string, symbol_count: number, } };
