// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Information about a local branch
 */
export type BranchInfo = { name: string, is_head: boolean, upstream: string | null, ahead: number, behind: number, };
