// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Status of Claude Code CLI setup and credential verification
 */
export type ClaudeSetupStatus = { 
/**
 * Whether the Claude CLI binary is installed
 */
cliInstalled: boolean, 
/**
 * Path to the Claude CLI binary (e.g. /usr/local/bin/claude)
 */
cliPath: string | null, 
/**
 * Whether OAuth credentials were found (keychain or file)
 */
credentialsFound: boolean, 
/**
 * Where the credentials came from: "keychain" or "credentials-file"
 */
credentialSource: string | null, 
/**
 * Whether the token is expired
 */
tokenExpired: boolean, 
/**
 * Token expiry timestamp (ms since epoch)
 */
tokenExpiresAt: number | null, 
/**
 * Seconds until token expires (negative if already expired)
 */
tokenExpiresInSeconds: number | null, 
/**
 * OAuth scopes on the token
 */
scopes: Array<string> | null, 
/**
 * Whether the token was verified against the API.
 * None = not checked, Some(true) = API call succeeded, Some(false) = rejected
 */
apiVerified: boolean | null, 
/**
 * Error message if something went wrong
 */
error: string | null, 
/**
 * Whether CLI mode is available (CLI installed + credentials found).
 * Subscription tokens require CLI mode; direct API calls won't work.
 */
cliModeAvailable: boolean, 
/**
 * Whether the credential is a subscription token that requires CLI mode.
 * These tokens cannot be used for direct API calls.
 */
requiresCliMode: boolean, };
