// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A content block within a message (supports text, tool use, and tool results)
 */
export type ContentBlock = { "type": "text", text: string, } | { "type": "tool_use", id: string, name: string, 
/**
 * JSON-encoded arguments
 */
arguments: string, } | { "type": "tool_result", tool_use_id: string, content: string, is_error: boolean, };
