// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to create a new worktree
 */
export type CreateWorktreeRequest = { 
/**
 * Branch name for the worktree
 */
branch: string, 
/**
 * Optional custom path (default: auto-generated)
 */
path: string | null, 
/**
 * Whether to create a new branch
 */
create_branch: boolean, 
/**
 * Base branch/ref to create from (default: HEAD)
 */
base: string | null, };
