// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single line in a unified diff
 */
export type DiffLine = { 
/**
 * Line kind: "context", "add", or "delete"
 */
kind: string, 
/**
 * Line content (without leading +/- marker)
 */
content: string, 
/**
 * Line number in old file (None for added lines)
 */
old_line_no: number | null, 
/**
 * Line number in new file (None for deleted lines)
 */
new_line_no: number | null, };
