// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to read a directory with lazy loading support
 */
export type DirectoryReadRequest = { 
/**
 * Path to the directory
 */
path: string, 
/**
 * Depth of children to include (0 = no children, 1 = immediate children only)
 */
depth: number, };
