// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileTreeEntry } from "./FileTreeEntry";

/**
 * Response with directory contents
 */
export type DirectoryReadResponse = { 
/**
 * Root entry with children
 */
entry: FileTreeEntry, 
/**
 * Total file count (for progress indication)
 */
total_count: number, };
