// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * TTS status event (emitted on "elevenlabs:tts_status" channel)
 */
export type ElevenLabsTtsStatusEvent = { session_id: string, status: string, error: string | null, };
