// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * STT status event (emitted on "elevenlabs:stt_status" channel)
 */
export type ElevenLabsSttStatusEvent = { session_id: string, status: string, error: string | null, };
