// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * TTS audio chunk event (emitted on "elevenlabs:tts_audio" channel)
 */
export type ElevenLabsTtsAudioEvent = { session_id: string, chunk: string, sample_rate: number, };
