// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * STT committed (final) transcript event (emitted on "elevenlabs:stt_committed" channel)
 */
export type ElevenLabsSttCommittedEvent = { session_id: string, text: string, };
