// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A file tree entry
 */
export type FileTreeEntry = { 
/**
 * Entry name
 */
name: string, 
/**
 * Full path
 */
path: string, 
/**
 * Whether this is a directory
 */
is_dir: boolean, 
/**
 * Children (for directories). None = not loaded, Some([]) = loaded but empty
 */
children: Array<FileTreeEntry> | null, 
/**
 * File size in bytes (for files)
 */
size: bigint | null, 
/**
 * Last modified timestamp (Unix epoch seconds)
 */
modified: bigint | null, };
