// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiffHunk } from "./DiffHunk";

/**
 * Full diff for a single file, with hunk-level detail
 */
export type FileDiff = { 
/**
 * Relative file path
 */
path: string, 
/**
 * Change status: "added", "modified", "deleted", "renamed"
 */
status: string, 
/**
 * Total lines added
 */
additions: number, 
/**
 * Total lines deleted
 */
deletions: number, 
/**
 * Diff hunks with line-level detail
 */
hunks: Array<DiffHunk>, };
