// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to rename/move a file or directory
 */
export type FileRenameRequest = { 
/**
 * Current path
 */
old_path: string, 
/**
 * New path
 */
new_path: string, };
