// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * File metadata information
 */
export type FileMetadata = { 
/**
 * File size in bytes
 */
size: bigint, 
/**
 * Whether this is a directory
 */
is_dir: boolean, 
/**
 * Whether this is a regular file
 */
is_file: boolean, 
/**
 * Last modified timestamp (Unix epoch seconds)
 */
modified: bigint | null, };
