// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to create a file or directory
 */
export type FileCreateRequest = { 
/**
 * Path where to create the file/directory
 */
path: string, 
/**
 * Whether to create a directory
 */
is_dir: boolean, 
/**
 * Initial content (for files only)
 */
content: string | null, };
