// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to delete a file or directory
 */
export type FileDeleteRequest = { 
/**
 * Path to delete
 */
path: string, 
/**
 * Whether to recursively delete directories
 */
recursive: boolean, };
