// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to write a file
 */
export type FileWriteRequest = { 
/**
 * Path to the file
 */
path: string, 
/**
 * Content to write
 */
content: string, };
