// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to read a file
 */
export type FileReadRequest = { 
/**
 * Path to the file
 */
path: string, };
