// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response with file contents
 */
export type FileReadResponse = { 
/**
 * File contents
 */
content: string, 
/**
 * File encoding
 */
encoding: string, };
