// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileErrorCode } from "./FileErrorCode";

/**
 * Error response for file operations
 */
export type FileOperationError = { 
/**
 * Error code for programmatic handling
 */
code: FileErrorCode, 
/**
 * Human-readable message
 */
message: string, 
/**
 * Path that caused the error
 */
path: string, };
