// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GitChangedFile } from "./GitChangedFile";
import type { GitChangesSummary } from "./GitChangesSummary";

/**
 * Response from git_get_changes
 */
export type GitChangesResponse = { 
/**
 * List of changed files
 */
files: Array<GitChangedFile>, 
/**
 * Aggregate summary
 */
summary: GitChangesSummary, };
