// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Summary of all changes
 */
export type GitChangesSummary = { 
/**
 * Total insertions across all files
 */
insertions: number, 
/**
 * Total deletions across all files
 */
deletions: number, };
