// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GitFileStatus } from "./GitFileStatus";

/**
 * A file that has been changed in git
 */
export type GitChangedFile = { 
/**
 * Relative file path
 */
path: string, 
/**
 * Change status
 */
status: GitFileStatus, 
/**
 * Number of inserted lines
 */
insertions: number, 
/**
 * Number of deleted lines
 */
deletions: number, };
