// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Status of a changed file in git
 */
export type GitFileStatus = "modified" | "added" | "deleted" | "renamed";
