// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response from git_get_file_diff
 */
export type GitFileDiffResponse = { 
/**
 * Old file content (from base ref)
 */
old_content: string, 
/**
 * New file content (current working tree)
 */
new_content: string, };
