// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of a git merge operation
 */
export type GitMergeResult = { fast_forward: boolean, conflicts: Array<string>, committed: boolean, };
