// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to push to GitHub
 */
export type GitPushRequest = { 
/**
 * GitHub access token
 */
access_token: string, 
/**
 * GitHub repository URL
 */
github_repo_url: string, 
/**
 * Branch name
 */
branch: string, 
/**
 * Commit message
 */
commit_message: string, };
