// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response from push
 */
export type GitPushResponse = { 
/**
 * Number of commits pushed
 */
commits_count: number, };
