// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response from pull
 */
export type GitPullResponse = { 
/**
 * Number of new commits pulled
 */
commits_count: number, 
/**
 * Warning message (e.g. stash pop conflict)
 */
warning: string | null, };
