// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to pull from GitHub
 */
export type GitPullRequest = { 
/**
 * GitHub access token
 */
access_token: string, 
/**
 * GitHub repository URL
 */
github_repo_url: string, 
/**
 * Branch name
 */
branch: string, 
/**
 * Whether to force reset (used for branch switching)
 */
force_reset: boolean, };
