// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Status of the git repository
 */
export type GitRepoStatus = { 
/**
 * Whether the workspace is a git repository
 */
is_repo: boolean, 
/**
 * Current branch name
 */
current_branch: string | null, 
/**
 * HEAD commit SHA
 */
head_sha: string | null, 
/**
 * Whether the repo has a github-integ remote
 */
has_remote: boolean, 
/**
 * Remote URL (if any)
 */
remote_url: string | null, 
/**
 * Number of commits ahead of remote (None if no remote or no tracking branch)
 */
commits_ahead: number | null, };
