// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to setup GitHub integration
 */
export type GitSetupRequest = { 
/**
 * GitHub repository URL (e.g. https://github.com/user/repo.git)
 */
github_repo_url: string, 
/**
 * Git username
 */
username: string, 
/**
 * Git email
 */
email: string, };
