// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SymbolRange } from "./SymbolRange";

/**
 * Parse error information
 */
export type ParseErrorInfo = { 
/**
 * Error message
 */
message: string, 
/**
 * Location of the error
 */
range: SymbolRange, };
