// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to parse a file
 */
export type ParseRequest = { 
/**
 * Path to the file
 */
path: string, 
/**
 * Optional content to parse (if not provided, reads from disk)
 */
content: string | null, };
