// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ParseErrorInfo } from "./ParseErrorInfo";
import type { Symbol } from "./Symbol";

/**
 * Response with parse results
 */
export type ParseResponse = { 
/**
 * Extracted symbols
 */
symbols: Array<Symbol>, 
/**
 * Parse errors found
 */
errors: Array<ParseErrorInfo>, 
/**
 * Time taken to parse (milliseconds)
 */
parse_time_ms: bigint, 
/**
 * Whether the tree has syntax errors
 */
has_errors: boolean, };
