// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to remove a worktree
 */
export type RemoveWorktreeRequest = { 
/**
 * Worktree ID to remove
 */
id: string, 
/**
 * Force removal even if dirty or locked
 */
force: boolean, };
