// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A range in source code (0-indexed)
 */
export type SymbolRange = { 
/**
 * Start line (0-indexed)
 */
start_line: number, 
/**
 * Start column (0-indexed)
 */
start_col: number, 
/**
 * End line (0-indexed)
 */
end_line: number, 
/**
 * End column (0-indexed)
 */
end_col: number, };
