// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Kind of symbol
 */
export type SymbolKind = "function" | "method" | "class" | "struct" | "enum" | "interface" | "type_alias" | "constant" | "variable" | "module" | "property" | "enum_member" | "trait" | "impl" | "macro" | "unknown";
