// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SymbolKind } from "./SymbolKind";
import type { SymbolRange } from "./SymbolRange";

/**
 * A symbol extracted from source code
 */
export type Symbol = { 
/**
 * Symbol name
 */
name: string, 
/**
 * Kind of symbol
 */
kind: SymbolKind, 
/**
 * Range in the source file
 */
range: SymbolRange, 
/**
 * Range of just the symbol name
 */
selection_range: SymbolRange, 
/**
 * Nested symbols
 */
children: Array<Symbol>, 
/**
 * Additional details
 */
detail: string | null, };
