// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to resize a terminal
 */
export type TerminalResizeRequest = { 
/**
 * Terminal ID
 */
id: string, 
/**
 * Number of columns
 */
cols: number, 
/**
 * Number of rows
 */
rows: number, };
