// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to write data to a terminal
 */
export type TerminalWriteRequest = { 
/**
 * Terminal ID
 */
id: string, 
/**
 * Data to write
 */
data: string, };
