// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to create a new terminal instance
 */
export type TerminalCreateRequest = { 
/**
 * Optional working directory
 */
cwd: string | null, 
/**
 * Optional shell override
 */
shell: string | null, 
/**
 * Optional environment variables
 */
env: { [key in string]?: string } | null, };
