// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentToolCall } from "./AgentToolCall";
import type { ToolCallStatus } from "./ToolCallStatus";

/**
 * A tool call with its current status and result
 */
export type ToolCallWithStatus = { 
/**
 * The tool call
 */
tool_call: AgentToolCall, 
/**
 * Current status
 */
status: ToolCallStatus, 
/**
 * Result (if completed)
 */
result: string | null, 
/**
 * Error message (if failed)
 */
error: string | null, 
/**
 * Whether this tool requires approval
 */
needs_approval: boolean, };
