// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Tool definition for registration
 */
export type ToolDefinitionProto = { 
/**
 * Tool name (unique identifier)
 */
name: string, 
/**
 * Human-readable description
 */
description: string, 
/**
 * JSON Schema for parameters (as JSON string)
 */
parameters: string, 
/**
 * Whether this tool requires user approval
 */
needs_approval: boolean, 
/**
 * Tool category for grouping
 */
category: string, };
