// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of a tool execution
 */
export type ToolResult = { 
/**
 * Tool call ID this result is for
 */
tool_call_id: string, 
/**
 * Whether execution succeeded
 */
success: boolean, 
/**
 * Result content (for success)
 */
content: string | null, 
/**
 * Error message (for failure)
 */
error: string | null, };
