// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Status of a tool call
 */
export type ToolCallStatus = "pending_approval" | "approved" | "rejected" | "running" | "completed" | "failed";
