// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to start watching a directory
 */
export type WatchRequest = { 
/**
 * Path to watch
 */
path: string, 
/**
 * Whether to watch recursively
 */
recursive: boolean, };
