// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single changed file in a worktree diff relative to its base branch.
 */
export type WorktreeDiffEntry = { 
/**
 * File path relative to repo root
 */
path: string, 
/**
 * Change status: "added", "modified", "deleted", "renamed"
 */
status: string, 
/**
 * Lines added (0 if unavailable)
 */
additions: number, 
/**
 * Lines removed (0 if unavailable)
 */
deletions: number, };
