// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Information about a git worktree
 */
export type WorktreeInfo = { 
/**
 * Unique worktree identifier
 */
id: string, 
/**
 * Filesystem path to the worktree
 */
path: string, 
/**
 * Branch checked out in this worktree
 */
branch: string | null, 
/**
 * HEAD commit SHA
 */
head_sha: string, 
/**
 * Whether this is the main (primary) worktree
 */
is_main: boolean, 
/**
 * Whether the worktree is locked
 */
is_locked: boolean, 
/**
 * Reason for locking
 */
lock_reason: string | null, 
/**
 * Whether the worktree has uncommitted changes
 */
is_dirty: boolean, 
/**
 * Agent session ID currently using this worktree
 */
agent_session_id: string | null, 
/**
 * Creation timestamp (Unix epoch seconds)
 */
created_at: bigint, };
