// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Setup commands to run after worktree creation (e.g., package install)
 */
export type WorktreeSetupConfig = { 
/**
 * Shell commands to run in the new worktree directory
 */
commands: Array<string>, };
