// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Model capabilities
 */
export type ModelCapabilities = { 
/**
 * Maximum context window (input tokens)
 */
context_window: number, 
/**
 * Maximum output tokens
 */
max_output_tokens: number, 
/**
 * Supports vision/images
 */
supports_vision: boolean, 
/**
 * Supports tool use
 */
supports_tools: boolean, 
/**
 * Supports streaming
 */
supports_streaming: boolean, 
/**
 * Has extended thinking capability
 */
supports_thinking: boolean, };
