// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderType } from "./ProviderType";

/**
 * Provider status information
 */
export type ProviderStatus = { provider_type: ProviderType, has_credentials: boolean, credential_source: string | null, is_active: boolean, available_models: Array<string>, };
