// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderType } from "./ProviderType";

/**
 * Provider configuration
 */
export type ProviderConfig = { provider_type: ProviderType, api_key: string | null, api_base_url: string | null, default_model: string | null, max_tokens: number | null, };
