#!/usr/bin/env bun
/**
 * Regenerate `infra/.env.<stage>` from live CloudFormation outputs so the
 * desktop app always reads client IDs that match what's actually deployed.
 *
 * Wired into `deploy:dev` / `deploy:prod`. Safe to run standalone after a
 * manual redeploy to refresh drifted env values.
 */

import { spawnSync } from "node:child_process";
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const INFRA_ROOT = path.resolve(__dirname, "..");

const stage = process.argv[2];
if (stage !== "dev" && stage !== "prod") {
  console.error(`Usage: sync-env.mjs <dev|prod>`);
  process.exit(1);
}

const profile = process.env.AWS_PROFILE ?? "solo";
const region = process.env.AWS_REGION ?? "us-east-1";

function aws(args) {
  const result = spawnSync("aws", args, { encoding: "utf8" });
  if (result.status !== 0) {
    throw new Error(`aws ${args.join(" ")} failed: ${result.stderr || result.stdout}`);
  }
  return JSON.parse(result.stdout);
}

function stackOutput(stackName) {
  const json = aws([
    "--profile", profile,
    "--region", region,
    "cloudformation", "describe-stacks",
    "--stack-name", stackName,
    "--query", "Stacks[0].Outputs",
    "--output", "json",
  ]);
  const map = {};
  for (const { OutputKey, OutputValue } of json) {
    map[OutputKey] = OutputValue;
  }
  return map;
}

console.log(`Syncing infra/.env.${stage} from CloudFormation stacks (profile=${profile}, region=${region})`);

const auth = stackOutput(`SoloAuth-${stage}`);
const envPath = path.join(INFRA_ROOT, `.env.${stage}`);

// Preserve any hand-managed keys (RDS password ARNs, etc) while overwriting
// the canonical AWS-derived ones.
const existing = existsSync(envPath) ? readFileSync(envPath, "utf8") : "";
const existingMap = new Map();
for (const line of existing.split(/\r?\n/)) {
  const m = line.match(/^([A-Z_][A-Z0-9_]*)\s*=\s*(.*)$/);
  if (m) existingMap.set(m[1], m[2]);
}

const authoritative = {
  SOLO_COGNITO_DOMAIN: `${auth.CognitoDomain}`,
  SOLO_COGNITO_USER_POOL_ID: auth.UserPoolId,
  SOLO_COGNITO_CLIENT_ID: auth.UserPoolClientId,
  SOLO_COGNITO_IDENTITY_POOL_ID: auth.IdentityPoolId,
  SOLO_AWS_REGION: region,
};

// Best-effort: pull API + GitHub wrapper endpoints if those stacks exist.
try {
  const api = stackOutput(`SoloApi-${stage}`);
  if (api.ApiEndpoint) authoritative.SOLO_API_ENDPOINT = api.ApiEndpoint;
} catch (e) {
  console.warn(`! SoloApi-${stage}: ${e.message.split("\n")[0]}`);
}
try {
  const gh = stackOutput(`SoloGitHub-${stage}`);
  const oidcIssuer = gh.OidcIssuerUrl ?? gh.OidcIssuer ?? gh.OidcApiUrl;
  const callbackUrl = gh.CallbackUrl ?? gh.GitHubCallbackUrl;
  if (oidcIssuer) authoritative.SOLO_GITHUB_OIDC_ISSUER = oidcIssuer;
  if (callbackUrl) authoritative.SOLO_GITHUB_CALLBACK = callbackUrl;
} catch (e) {
  console.warn(`! SoloGitHub-${stage}: ${e.message.split("\n")[0]}`);
}

const merged = new Map(existingMap);
for (const [k, v] of Object.entries(authoritative)) {
  if (v !== undefined) merged.set(k, v);
}

const ordered = [
  "SOLO_COGNITO_DOMAIN",
  "SOLO_COGNITO_USER_POOL_ID",
  "SOLO_COGNITO_CLIENT_ID",
  "SOLO_COGNITO_IDENTITY_POOL_ID",
  "SOLO_AWS_REGION",
  "SOLO_API_ENDPOINT",
  "SOLO_GITHUB_OIDC_ISSUER",
  "SOLO_GITHUB_CALLBACK",
  "SOLO_RDS_ENDPOINT",
  "SOLO_RDS_PORT",
  "SOLO_RDS_DATABASE",
  "SOLO_RDS_SECRET_ARN",
];

const seen = new Set(ordered);
const trailing = [...merged.keys()].filter((k) => !seen.has(k));

const header = [
  `# Solo IDE — ${stage} stage AWS outputs (public identifiers, safe to commit)`,
  `# Generated by \`bun run sync-env ${stage}\` (run automatically after \`deploy:${stage}\`).`,
  `# These are NOT secrets — Cognito pool IDs are public by design.`,
  ``,
].join("\n");

const body = [...ordered, ...trailing]
  .filter((k) => merged.has(k))
  .map((k) => `${k}=${merged.get(k)}`)
  .join("\n");

writeFileSync(envPath, `${header}${body}\n`);

const changed = [];
for (const [k, v] of Object.entries(authoritative)) {
  if (existingMap.get(k) !== v) changed.push(`  ${k}: ${existingMap.get(k) ?? "(unset)"} -> ${v}`);
}
if (changed.length === 0) {
  console.log(`.env.${stage} already in sync — no changes.`);
} else {
  console.log(`Updated .env.${stage}:`);
  for (const line of changed) console.log(line);
}
