// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelCapabilities } from "./ModelCapabilities";
import type { ProviderType } from "./ProviderType";

/**
 * AI Model definition
 */
export type AIModel = { 
/**
 * Model ID (e.g., "claude-sonnet-4-20250514")
 */
id: string, 
/**
 * Display name (e.g., "Claude Sonnet 4")
 */
display_name: string, 
/**
 * Short alias (e.g., "sonnet")
 */
alias: string, 
/**
 * Provider type
 */
provider: ProviderType, 
/**
 * Model capabilities
 */
capabilities: ModelCapabilities, 
/**
 * Whether this is the default model for the provider
 */
is_default: boolean, 
/**
 * Description
 */
description: string, };
