// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuthType } from "./AuthType";

/**
 * Authentication method info for display
 */
export type AuthMethodInfo = { 
/**
 * Type of authentication
 */
authType: AuthType, 
/**
 * Whether currently authenticated
 */
isAuthenticated: boolean, 
/**
 * Seconds until token expires (None for API keys)
 */
expiresInSeconds: bigint | null, 
/**
 * Source of the credential
 */
credentialSource: string | null, };
