// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result from starting an OAuth flow
 */
export type OAuthFlowResult = { 
/**
 * The authorization URL to open
 */
auth_url: string, 
/**
 * State parameter to verify callback
 */
state: string, };
