// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * OAuth flow method (browser or manual code entry)
 */
export type OAuthMethod = "browser" | "paste-code";
