// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderType } from "./ProviderType";

/**
 * Provider status information
 */
export type ProviderStatus = { 
/**
 * Provider type
 */
provider_type: ProviderType, 
/**
 * Whether credentials are configured
 */
has_credentials: boolean, 
/**
 * Source of credentials (env, keychain, etc.)
 */
credential_source: string | null, 
/**
 * Whether the provider is currently active
 */
is_active: boolean, 
/**
 * Available models for this provider
 */
available_models: Array<string>, };
