// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderType } from "./ProviderType";

/**
 * Provider configuration
 */
export type ProviderConfig = { 
/**
 * Provider type
 */
provider_type: ProviderType, 
/**
 * API key (not serialized for security)
 */
api_key: string | null, 
/**
 * Custom API base URL (for proxies or self-hosted)
 */
api_base_url: string | null, 
/**
 * Default model to use
 */
default_model: string | null, 
/**
 * Maximum tokens for responses
 */
max_tokens: number | null, };
