/**
 * Generate barrel (index.ts) for the bindings directory.
 * Run automatically as part of `bun run gen:bindings`.
 */

import { readdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const bindingsDir = join(import.meta.dirname, '..', 'apps', 'desktop', 'src', 'bindings');

const files = readdirSync(bindingsDir)
  .filter(f => f.endsWith('.ts') && f !== 'index.ts')
  .sort();

let out = '// This file is auto-generated by gen:bindings. Do not hand-edit.\n\n';

for (const f of files) {
  const name = f.replace('.ts', '');
  out += `export type { ${name} } from './${name}';\n`;
}

out += `
// Agent bridge protocol types (hand-maintained, not generated by ts-rs)
export type {
\tAgentErrorEvent,
\tAgentMessageEvent,
\tAgentModeChangedEvent,
\tAgentPermissionRequestEvent,
\tAgentSessionInitEvent,
\tAgentTurnStartEvent,
\tAttachmentContentBlock,
\tBridgeAgentMessage,
\tPermissionRequest,
\tProviderCapabilities,
\tSessionConfig,
\tTokenUsage,
\tToolPolicyConfig,
} from '../types/agent-protocol';
`;

writeFileSync(join(bindingsDir, 'index.ts'), out);
console.log(`Generated bindings barrel with ${files.length} type exports.`);
