/**
 * Agent Bridge Protocol Types
 *
 * Hand-maintained types mirroring the agent-bridge sidecar's IPC protocol.
 * These types are NOT auto-generated by ts-rs — they originate in the Node.js
 * agent-bridge and are forwarded by the Rust backend as Tauri events.
 *
 * Source of truth: agent-bridge/src/session-manager.ts, agent-bridge/src/messages.ts
 */

// =============================================================================
// Core Agent Types
// =============================================================================

export interface TokenUsage {
	inputTokens: number;
	outputTokens: number;
	cacheReadInputTokens?: number;
	cacheCreationInputTokens?: number;
}

export interface BridgeAgentMessage {
	type: 'text' | 'thinking' | 'tool_use' | 'result' | 'error';
	content: string;
	metadata?: {
		toolName?: string;
		toolId?: string;
		toolInput?: Record<string, unknown>;
		toolOutput?: string;
		status?: 'awaiting-permission' | 'running' | 'success' | 'error';
	};
	usage?: TokenUsage;
	totalCostUsd?: number;
	durationMs?: number;
	structuredOutput?: unknown;
	resultSubtype?: string;
}

export interface PermissionRequest {
	sessionId: string;
	toolName: string;
	toolInput: Record<string, unknown>;
	requestId: string;
}

export interface AttachmentContentBlock {
	type: 'document' | 'image' | 'text';
	source?: {
		type: 'base64';
		mediaType: string;
		data: string;
	};
	text?: string;
	name?: string;
	filePath?: string;
	lineStart?: number;
	lineEnd?: number;
	terminalName?: string;
	timestamp?: string;
}

export interface SessionConfig {
	cwd?: string;
	thinkingEnabled?: boolean;
	maxThinkingTokens?: number;
	planEnabled?: boolean;
	acceptEnabled?: boolean;
	critiqueEnabled?: boolean;
	model?: 'haiku' | 'sonnet' | 'opus';
	sessionMode?: 'chat' | 'agent';
	resumeSessionId?: string;
	forkSession?: boolean;
}

// =============================================================================
// Tauri Event Payloads
// =============================================================================

export interface AgentMessageEvent {
	sessionId: string;
	message: BridgeAgentMessage;
}

export interface AgentPermissionRequestEvent {
	sessionId: string;
	toolName: string;
	toolInput: Record<string, unknown>;
	requestId: string;
}

export interface AgentSessionInitEvent {
	sessionId: string;
	sdkSessionId: string;
	isResumed: boolean;
	isForked: boolean;
}

export interface AgentModeChangedEvent {
	sessionId: string;
	enabled: boolean;
}

export interface AgentTurnStartEvent {
	sessionId: string;
	turnNumber: number;
}

export interface AgentErrorEvent {
	message: string;
	stack?: string;
}
