/**
 * Agent Bridge Protocol Types
 *
 * Hand-maintained types mirroring the agent-bridge sidecar's IPC protocol.
 * These types are NOT auto-generated by ts-rs — they originate in the Node.js
 * agent-bridge and are forwarded by the Rust backend as Tauri events.
 *
 * Source of truth: agent-bridge/src/session-manager.ts, agent-bridge/src/messages.ts
 */

// =============================================================================
// Core Agent Types
// =============================================================================

export interface TokenUsage {
	inputTokens: number;
	outputTokens: number;
	cacheReadInputTokens?: number;
	cacheCreationInputTokens?: number;
}

export interface BridgeAgentMessage {
	type: 'turn_start' | 'text' | 'thinking' | 'tool_use' | 'tool_result' | 'result' | 'error';
	content: string;
	eventId?: string;
	turnNumber?: number;
	sdkSessionId?: string;
	metadata?: {
		toolName?: string;
		toolId?: string;
		toolInput?: Record<string, unknown>;
		toolOutput?: string;
		status?: 'awaiting-permission' | 'running' | 'success' | 'error';
	};
	usage?: TokenUsage;
	totalCostUsd?: number;
	durationMs?: number;
	structuredOutput?: unknown;
	resultSubtype?: string;
}

export interface PermissionRequest {
	sessionId: string;
	toolName: string;
	toolInput: Record<string, unknown>;
	requestId: string;
}

export interface AttachmentContentBlock {
	type: 'document' | 'image' | 'text';
	source?: {
		type: 'base64';
		mediaType: string;
		data: string;
	};
	text?: string;
	name?: string;
	filePath?: string;
	lineStart?: number;
	lineEnd?: number;
	terminalName?: string;
	timestamp?: string;
}

export interface ProviderCapabilities {
	chat: boolean;
	agent: boolean;
	tools: boolean;
	mcp: boolean;
	resume: boolean;
}

export interface ToolPolicyConfig {
	allow?: string[];
	deny?: string[];
	ask?: string[];
	bashAllowPrefixes?: string[];
	bypassEnabled?: boolean;
	isWorktreeSession?: boolean;
}

export interface SessionConfig {
	cwd?: string;
	thinkingEnabled?: boolean;
	maxThinkingTokens?: number;
	/** Output-token cap per response (forwarded to SDK via env var) */
	maxTokens?: number;
	/**
	 * Explicit per-session tool allow-list. When provided the bridge installs
	 * `options.allowedTools = allowedTools` on the SDK and no other tools are
	 * callable. Used by the Git Agent harness to constrain the model to git +
	 * read-only file operations so a prompt-escape can't run arbitrary code.
	 */
	allowedTools?: string[];
	selectedSkills?: string[];
	mcpServers?: Record<string, unknown>;
	outputFormat?: unknown;
	agents?: Record<string, unknown>;
	toolPolicy?: ToolPolicyConfig;
	permissionMode?: 'default' | 'plan' | 'accept' | 'debug';
	providerCapabilities?: ProviderCapabilities;
	planEnabled?: boolean;
	acceptEnabled?: boolean;
	critiqueEnabled?: boolean;
	model?: string;
	sessionMode?: 'chat' | 'agent';
	resumeSessionId?: string;
	forkSession?: boolean;
	provider?: 'anthropic' | 'openai' | 'google' | 'gemini';
}

// =============================================================================
// Tauri Event Payloads
// =============================================================================

export interface AgentMessageEvent {
	sessionId: string;
	message: BridgeAgentMessage;
}

export interface AgentPermissionRequestEvent {
	sessionId: string;
	toolName: string;
	toolInput: Record<string, unknown>;
	requestId: string;
}

export interface AgentSessionInitEvent {
	sessionId: string;
	sdkSessionId: string;
	isResumed: boolean;
	isForked: boolean;
}

export interface AgentModeChangedEvent {
	sessionId: string;
	enabled: boolean;
}

export interface AgentTurnStartEvent {
	sessionId: string;
	turnNumber: number;
}

export interface AgentErrorEvent {
	message: string;
	stack?: string;
}
